<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Furniture;

class FurnitureSeeder extends Seeder
{
    public function run(): void
    {
        $furnitures = [
            // Sofas & Armchairs

            [
                'name' => 'Soriana Sofa',
                'price' => 8100,
                'image' => '/assets/images/furnitures/soriana_sofa.PNG',
                'category' => 'Sofas & Armchairs',
                'alt' => 'Ultra-soft “hot-dog” style sofa you would not want to leave',
                'description' => "Afra & Tobia Scarpa's revolutionary 1969 Soriana sofa for Cassina redefined upholstered furniture by eliminating internal support, relying instead on a metal clamp structure that embraces foam padding like a sculptural embrace. This 1970 Compasso d'Oro winner combines comfort with avant-garde design, featuring quilted upholstery and organic curves that embody the era's relaxed lifestyle philosophy.",
                'measurements' => '175 W x 105 D x 71 H cm',
                'color' => 'brown',
                'material' => 'leather',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name' => 'Cassina LC3 Sofa',
                'price' => 6300,
                'image' => '/assets/images/furnitures/cassina_lc3_sofa.PNG',
                'category' => 'Sofas & Armchairs',
                'alt' => 'Robust yet plush jet-black sofa on a steel base',
                'description' => "Le Corbusier, Pierre Jeanneret, and Charlotte Perriand's 1928 LC3 'Grand Confort' transforms the traditional club chair into a modernist masterpiece with chrome tubular steel framing thick leather cushions. This rationalist design separates the metal cage from upholstered elements, expressing the era's industrial production aesthetic while delivering luxurious comfort.",
                'measurements' => '180 W x 70 D x 67 H cm',
                'color' => 'black',
                'material' => 'leather',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Togo Sofa',
                'price' => 5500,
                'image' => '/assets/images/furnitures/togo_sofa.PNG',
                'category' => 'Sofas & Armchairs',
                'alt' => 'Four-piece, seven-seat corner sofa in leaf green with a large matching ottoman',
                'description' => "Michel Ducaroy's iconic 1973 Togo sofa for Ligne Roset was inspired by a crumpled toothpaste tube, creating furniture that 'wallows' close to the ground with distinctive quilted pleats. This revolutionary design uses multiple-density polyurethane foam construction without internal framework, becoming a symbol of relaxed 1970s living and selling over one million copies worldwide.",
                'measurements' => '170 W x 102 D x 71 H cm',
                'color' => 'green',
                'material' => 'leather',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Eames Lounge Chair and Ottoman',
                'price' => 4000,
                'image' => '/assets/images/furnitures/eames_lounge_chair.PNG',
                'category' => 'Sofas & Armchairs',
                'alt' => 'Fully adjustable leather lounge chair with matching plush ottoman; modular for custom comfort',
                'description' => "Charles and Ray Eames' 1956 masterpiece for Herman Miller epitomizes luxurious comfort with seven-ply molded wood shells, button-tufted leather cushions, and a swiveling aluminum base - famously described as having 'the warm receptive look of a well-used first baseman's mitt.' This design icon remains in continuous production and represents one of the 20th century's most significant furniture pieces.",
                'measurements' => '85 W x 89 D x 80 H cm',
                'color' => 'brown',
                'material' => 'leather',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Chairs & Benches
            [
                'name' => 'Set of 4 Cesca Chairs',
                'price' => 1600,
                'image' => '/assets/images/furnitures/cesca_chairs.jpg',
                'category' => 'Chairs & Benches',
                'alt' => 'Set of four cantilever chairs S-shaped front leg flowing into the backrest; seat and back in woven bamboo cane',
                'description' => "Marcel Breuer's 1928 Cesca chair for the Bauhaus marries traditional craftsmanship with industrial tubular steel in a revolutionary cantilever design named after his daughter Francesca. This hand-woven cane and chrome steel masterpiece exploits the material's flexibility for added comfort while embodying modernist principles of function and form.",
                'measurements' => '47 W x 50 D x 81 H cm',
                'color' => 'light brown',
                'material' => 'rattan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Wassily Chair',
                'price' => 2500,
                'image' => '/assets/images/furnitures/wassily_chair.jpg',
                'category' => 'Chairs & Benches',
                'alt' => 'Leather sling chair on aluminum frame; close armrests with extra leather tabs for better posture',
                'description' => "Marcel Breuer's 1925 B3 'Wassily' chair - named after Bauhaus colleague Wassily Kandinsky who admired the design - represents the first tubular steel furniture piece, inspired by bicycle handlebars. This constructivist club chair strips away traditional stuffing, leaving a skeletal chrome frame with stretched leather seat, back, and arms that revolutionized modern furniture design.",
                'measurements' => '77 W x 67 D x 74 H cm',
                'color' => 'brown',
                'material' => 'leather',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Set of 2 Butterfly Chairs',
                'price' => 2000,
                'image' => '/assets/images/furnitures/butterfly_chairs.jpg',
                'category' => 'Chairs & Benches',
                'alt' => 'Cocoon-shaped tanned-leather chairs that cradle you like small hammocks',
                'description' => "Jorge Ferrari Hardoy, Antonio Bonet, and Juan Kurchan's iconic 1938 BKF (Butterfly) chair revolutionized portable seating with its suspended leather sling hung from a sculptural metal frame designed for Le Corbusier's studio in Buenos Aires. This MoMA-acclaimed design earned second prize at Argentina's 3rd Salón de Artistas Decoradores and became a sensation when produced by Knoll from 1948-1951, epitomizing relaxed modernist living.",
                'measurements' => '80 W x 76 D x 87 H cm',
                'color' => 'brown',
                'material' => 'leather',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Set of 10 Wishbone Chairs',
                'price' => 7500,
                'image' => '/assets/images/furnitures/whishbone_chairs.jpg',
                'category' => 'Chairs & Benches',
                'alt' => 'Set of ten blue-green steel chairs with rounded backs and flexible woven-reed seats',
                'description' => "Hans J. Wegner's 1949 CH24 'Wishbone' chair for Carl Hansen & Søn represents the pinnacle of Danish craftsmanship, combining the back and armrest into a single graceful piece with a distinctive Y-shaped support that gives the chair its name. Each chair requires over 100 hand-crafted steps including an hour of weaving 120 meters of paper cord for the seat, creating Wegner's most successful and continuously produced design.",
                'measurements' => '55 W x 51 D x 76 H cm',
                'color' => 'green',
                'material' => 'wood',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Shelves & Storage
            [
                'name' => 'Michael Draper Shelving Unit',
                'price' => 2400,
                'image' => '/assets/images/furnitures/michael_draper_shelving_unit.PNG',
                'category' => 'Shelves & Storage',
                'alt' => 'Multi-purpose shelving—two large drawers, three high shelves, one low shelf; light wood and aluminium with an ochre-yellow accent',
                'description' => "Michael Draper's innovative steel shelving unit represents the pinnacle of New Zealand contemporary design, created in collaboration with award-winning architect Pete Bossley from Draper's Ponsonby workshop. This Northern Ireland-born designer revolutionized steel furniture in the 1970s with his minimalist aesthetic and exceptional craftsmanship, creating pieces built to last lifetimes. The linear design features beautiful drawers and adjustable shelves that demonstrate thoughtful functionality perfect for contemporary spaces. ",
                'measurements' => '120 W x 35 D x 200 H cm',
                'color' => 'light brown',
                'material' => 'wood',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Poul Cadovius Shelving Unit',
                'price' => 3000,
                'image' => '/assets/images/furnitures/poul_cadovius_shelving_unit.PNG',
                'category' => 'Shelves & Storage',
                'alt' => 'Wall-mounted oak system with four deep lower drawers, two upper sliding doors, and six open shelves—perfect for an entryway',
                'description' => "Poul Cadovius's revolutionary 1948 Royal System transformed storage design as the world's first wall-mounted modular shelving system, earning gold at the Finland Furniture Fair in 1950 and silver at Milan's XI Triennale in 1957. This Danish innovation maximized floor space through floating teak shelves suspended on brass hangers, with over 400 patents behind his minimalist designs that perfectly harmonize form and function.",
                'measurements' => '80 W x 30 D x 150 H cm',
                'color' => 'brown',
                'material' => 'wood',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Adam Wood Shelves',
                'price' => 1200,
                'image' => '/assets/images/furnitures/adam_wood_shelves.jpg',
                'category' => 'Shelves & Storage',
                'alt' => 'Three columns of finely cut wooden shelves on steel uprights',
                'description' => "Ron Arad's innovative Adam Wood shelving system for Kartell represents a bold fusion of traditional wood craftsmanship with contemporary Italian design, featuring modular oak components that can be configured in countless arrangements. This modern classic demonstrates Kartell's commitment to pushing material boundaries while maintaining functional elegance through Arad's sculptural sensibility.",
                'measurements' => '80 W x 25 D x 180 H cm',
                'color' => 'brown',
                'material' => 'wood',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'USM Haller Dresser',
                'price' => 1500,
                'image' => '/assets/images/furnitures/usm_haller_dresser.PNG',
                'category' => 'Shelves & Storage',
                'alt' => 'Low storage unit with two large drop-down doors and two shelves; light-green aluminum body with glass top',
                'description' => "Fritz Haller and Paul Schärer's revolutionary 1963 modular furniture system for USM transforms storage through chrome-plated steel balls connecting powder-coated tubes and panels, creating infinitely adaptable configurations. This Swiss design classic, featured in MoMA's collection, embodies the 'form follows function' principle with its distinctive modular construction that can be endlessly reconfigured and expanded.",
                'measurements' => '75 W x 35 D x 75 H cm',
                'color' => 'green',
                'material' => 'steel',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Tables & Desks
            [
                'name' => 'Noguchi Coffee Table',
                'price' => 4000,
                'image' => '/assets/images/furnitures/noguchi_coffee_table.jpg',
                'category' => 'Tables & Desks',
                'alt' => 'Triangular glass-top coffee table with rounded edges on interlocking U-shaped wooden legs',
                'description' => "Isamu Noguchi's sculptural 1948 masterpiece for Herman Miller balances organic artistry with functional brilliance through two interlocking curved wood pieces supporting a thick glass top, embodying the artist's philosophy that 'everything is sculpture.' This registered trademark design features Noguchi's signature etched on both the glass edge and base, making it one of America's most iconic coffee tables.",
                'measurements' => '127 W x 91 D x 40 H cm',
                'color' => 'light brown',
                'material' => 'glass',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '529 Rio Coffee Table',
                'price' => 1200,
                'image' => '/assets/images/furnitures/529_rio_coffee_table.jpg',
                'category' => 'Tables & Desks',
                'alt' => 'Nearly round coffee table split into six wedges, each showing oak wood and white-marble inlay',
                'description' => "Mid-century Brazilian modern coffee table featuring a distinctive rectangular rosewood top supported by sleek tapered legs, exemplifying the sophisticated furniture design emerging from São Paulo's modernist movement in the 1960s. This piece represents the golden age of Brazilian design when local craftsmen created furniture that rivaled European modernist masters.",
                'measurements' => '120 W x 60 D x 40 H cm',
                'color' => 'light brown',
                'material' => 'marble',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Saarinen Tulip Dining Table',
                'price' => 7500,
                'image' => '/assets/images/furnitures/saarinen_tulip_table.jpg',
                'category' => 'Tables & Desks',
                'alt' => 'White polyester dining set—round pedestal table plus six chairs with midnight-blue seat cushions',
                'description' => "Eero Saarinen's iconic 1958 Pedestal 'Tulip' table for Knoll eliminated 'the slum of legs' underneath traditional tables through his sculptural single-column design that flares into a circular cast aluminum base. This modernist masterpiece, perfected over five years, combines structural elegance with timeless appeal, becoming a symbol of mid-century design that remains a Knoll mainstay today.",
                'measurements' => '120 W x 120 D x 72 H cm',
                'color' => 'white',
                'material' => 'marble',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Laccio 2 Coffee Table',
                'price' => 1400,
                'image' => '/assets/images/furnitures/laccio_2_coffee_table.jpg',
                'category' => 'Tables & Desks',
                'alt' => 'Rectangular polyester coffee table on a light aluminium base, topped by a smaller tray-like over-table',
                'description' => "Marcel Breuer's revolutionary 1925 Laccio table series epitomizes Bauhaus design philosophy with its tubular steel frame inspired by bicycle construction and minimal black laminate top. Created when Breuer was just 23 as a companion to his Wassily chair, this geometric masterpiece demonstrates the school's mission to reconcile art and industry through bold, functional design.",
                'measurements' => '95 W x 55 D x 33 H cm',
                'color' => 'white',
                'material' => 'wood',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Beds
            [
                'name' => 'Nelson Thin Edge Bed',
                'price' => 3000,
                'image' => '/assets/images/furnitures/nelson_thin_edge_bed.PNG',
                'category' => 'Beds',
                'alt' => 'Complete queen-size bed with slatted base, suede headboard, and two beige bedside tables with drawers',
                'description' => "George Nelson's 1954 Thin Edge Bed epitomizes his timeless, human-centered modernist approach with its slim horizontal profile, precise detailing, and expert woodcraft that brings elegant minimalism to the bedroom. Reintroduced by Herman Miller using archive studies, this design now features updated slats for memory foam mattresses while maintaining Nelson's exceptional simplicity and clarity through clean lines and sophisticated refinement.",
                'measurements' => '170 W x 200 D x 90 H cm',
                'color' => 'beige',
                'material' => 'wood',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Conoid Bed',
                'price' => 18000,
                'image' => '/assets/images/furnitures/conoid_bed.jpg',
                'category' => 'Beds',
                'alt' => 'Solid oak platform bed with bookshelf/night-table headboard and sliding-door storage',
                'description' => "George Nakashima's Conoid bed exemplifies his reverence for wood through live-edge American walnut construction with signature butterfly joints that celebrate natural imperfections rather than hiding them. This master craftsman's design philosophy of giving trees 'a second life' created furniture that blurs the line between art and utility, with pieces now commanding premium prices at auction.",
                'measurements' => '170 W x 200 D x 90 H cm',
                'color' => 'brown',
                'material' => 'wood',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Classic Day Bed',
                'price' => 12000,
                'image' => '/assets/images/furnitures/classic_day_bed.jpg',
                'category' => 'Beds',
                'alt' => 'Natural, elegant king-size Japanese-style platform bed in acacia wood',
                'description' => "George Nakashima's Classic Day Bed embodies his philosophy of giving trees 'a second life' through carefully selected solid wood construction that celebrates natural grain patterns and live edges. This master craftsman's approach to furniture as spiritual practice resulted in pieces that blur the line between functional seating and sculptural art, with each piece reflecting his deep reverence for the inherent beauty of wood.",
                'measurements' => '200 W x 80 D x 75 H cm',
                'color' => 'brown',
                'material' => 'wood',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tricoire & Vecchione Teak Bed',
                'price' => 1500,
                'image' => '/assets/images/furnitures/tricoire_vecchione_teak_bed.PNG',
                'category' => 'Beds',
                'alt' => 'Platform bed with integrated headboard and nightstands in golden light acacia wood',
                'description' => "French design duo's elegant teak platform bed from the 1960s showcases sophisticated joinery techniques and warm wood tones characteristic of European mid-century bedroom furniture. Their collaborative approach resulted in pieces that balanced sculptural form with practical function, earning recognition among collectors of refined modernist design.",
                'measurements' => '175 W x 210 D x 85 H cm',
                'color' => 'brown',
                'material' => 'wood',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        Furniture::insert($furnitures);
    }
}